### ISSUE TITLE
Folding stops working with clojure-lsp 2024.03.31-19.10.13 and folding strategy auto

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#2486]
With clojure-lsp `2024.03.31-19.10.13` came folding support. Surprisingly (to me) this makes folding stop working for users who have the **Folding Stratey** set to the default, **auto**. Setting it to **indentation** makes it start working again (but it's the old boring folding, not the the clojure-lsp one).

![image](https://github.com/BetterThanTomorrow/calva/assets/30010/cc50c161-b5d9-4743-a300-7a8513a13d54)

I see this in the clojure-lsp trace log:

```
[Trace - 10:35:10 AM] Sending request 'textDocument/foldingRange - (12)'.
Params: {
    "textDocument": {
        "uri": "..."
    }
}


[Trace - 10:35:10 AM] Received response 'textDocument/foldingRange - (12)' in 2ms.
Result: [
    {
        "startLine": 1,
        "startCharacter": 5,
        "endLine": 1,
        "endCharacter": 37,
        "kind": "region"
    },
    {
        "startLine": 8,
        "startCharacter": 8,
        "endLine": 8,
        "endCharacter": 13,
        "kind": "region"
    }
]
```

Which looks perfectly fine for the file in question.

Something obviously needs to change in Calva to enable the support, but I don't know what it could be. CC:

* @bpringe 
* @maxrothman 
* @ericdallo

**Comment by EvaMarco** [comment]
I came to say this :), I'm glad you already knew

**Comment by ericdallo** [comment]
clojure-lsp was using the name range instead of the scope one, fixed in master, available as a nightly build.

**Comment by PEZ** [comment]
The easiest way to use the nightly build is like so:

<img width="467" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/ce15fb2e-444f-4910-baa6-cbc09201b7ee">

Then reload the VS Code window. The info about that it takes effect on restart of clojure-lsp is false I realized today. Need to look at that. But a reload of the VS Code window works.

**Comment by EvaMarco** [comment]
Thanks is working for me with this change

**Comment by FalseProtagonist** [comment]
I'm still getting some weird behavior after changing to nightly and reloading. Now folding kind of works, but lvl3 folding etc doesn't work, folding whilst indented using z-c used to only fold the (nearest) enclosing form but not closes the outermost enclosing form.

**Comment by PEZ** [comment]
@FalseProtagonist the fix for you is probably to keep using the old folding strategy, by setting it explicitly as described in the OP.

For feedback on the actual folding provided by clojure-lsp, I say bring to the clojure-lsp team.

**Comment by sirmspencer** [comment]
Is there a thread for this on clojure-lsp to follow?  This is still an issue.  nightly no longer fixes it.
