### ISSUE TITLE
Keep focus in editor when using send form to terminal repl

### ISSUE THREAD

**Issue by LukeDefeo** [BetterThanTomorrow/calva#59]
It would be good you didnt have to keep switching back to the source code buffer every time you evaluate an expression

**Comment by PEZ** [comment]
Hello! Nice to get some feedback on this. When I implemented it I think there was no way to show the pane without also giving it focus. But I might remember it wrong, maybe I just did the wrong call. I agree that if it is possible, focus should remain in the editor.

**Comment by PEZ** [comment]
I've published your fix for this now. It really is much better when the focus stays in the editor. Thanks!

**Comment by armed** [comment]
Hi, is this behavior changed in 2.0? Usually I have list of forms in large comment blocks and evaluate forms one by one to see results. Focusing on repl distracts this flow.

**Comment by PEZ** [comment]
@armed , can you open an issue about what behaviour you see and what you would like to see?

**Comment by armed** [comment]
Hey, @PEZ. I think I missed something. I'm still using 1.x version (1.3.0). So question about 2.0 is not relevant.
But I've same issue as described here. REPL window is focused whenever I eval form from `comment` block from inside the editor window. I mean at least in my configuration this issue is not fixed (should we reopen it?).

**Comment by PEZ** [comment]
Ah, well, there is not much of a point with opening issues on `1.3.x` stuff. That version is going to be killed soon.
